
enum STATUS {
  // SUCCESS
  SUCCESS = 200,
  REG_ACCEPT = 201,
  // ERRORS
  BAD_REQUEST_ERR = 400,
  AUTH_ERR = 401,
  RESOURCE_NOT_FOUND_ERR = 404,

  SERVER_ERR = 500,

  RESOURCE_MISMATCH_ERR = 1304,

  INVALID_ENCODING_ERR = 1400,
  CYCLE_REJECTED_ERR = 1403,
  CYCLE_NOT_FOUND_ERR = 1404,

  // INTERNAL NON-RETRYABLE ERRORS
  JSON_PARSE_ERR = 5000,
  EXECUTOR_LOAD_MODEL_ERR = 5001,
  TERMINAL_ERROR = 5002,
  // INTERNAL RETRYABLE ERRORS
  RETRYABLE_ERROR = -1,

  // JNI ERRORS
  DATA_TYPE_NOT_SUPPORTED_ERROR = 2001,
};

enum DATATYPE { PREPROCESSOR_INPUT_TYPE = 666 };

#define MODELDOWNLOADMETRIC "modelDownload"
#define PINGMETRIC "pingTime"
#define INFERENCEMETRIC "inference"
#define STATICDEVICEMETRICS "staticDevice"
#define DYNAMICDEVICEMETRICS "dynamicDevice"